### ISSUE TITLE
1.5版本安装模块报错  No matching distribution found for lib.whois  ，怎末解决

### ISSUE THREAD

**Issue by sdfwesfe** [kracer127/SiteScan#6]

**Comment by kracer127** [comment]
试试手动安装：pip install whois

**Comment by nasdadadada** [comment]
升级了也不可以 还是显示这个 删了重新下都还是报错

**Comment by nasdadadada** [comment]
没事了 自己捣鼓好了 
from whois import whois

**Comment by kracer127** [comment]
你应该是在mac上运行的吧，windows上我测试好几遍都没问题，实在不行就手动request.py里导入：from whois import whois

**Comment by nasdadadada** [comment]
谢谢啊 师傅 我刚刚已经捣鼓出来了 
 捣鼓完就回了

**Comment by shilei990** [comment]
我windows也是一堆报错
PS C:\Users\Stone\Documents\GitHub\SiteScan> python3.12.exe .\main.py -u http://114.80.215.103
C:\Users\Stone\Documents\GitHub\SiteScan\main.py:18: SyntaxWarning: invalid escape sequence '\_'
  logo = '''\033[1;32m
Traceback (most recent call last):
  File "C:\Users\Stone\Documents\GitHub\SiteScan\main.py", line 6, in <module>
    from request import *   # 获取返回内容
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stone\Documents\GitHub\SiteScan\request.py", line 8, in <module>
    from lib.whois import whois
  File "C:\Users\Stone\Documents\GitHub\SiteScan\lib\whois\__init__.py", line 7, in <module>
    from future import standard_library
  File "c:\python312\Lib\site-packages\future\standard_library\__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by kracer127** [comment]
使用python版本不要超过3.10

**Comment by yellowhai** [comment]
python3.11,解决不了，裂开
